"""Core immutable data structures passed between backend modules.

These dataclasses intentionally stay very small. They act as strongly typed
containers for the generated ticket, the generated draw, and the evaluation
result. Using frozen dataclasses protects the simulation from accidental
mutations while the same objects are reused by multiple helper functions.
"""

from dataclasses import dataclass
from typing import FrozenSet


@dataclass(frozen=True)
class Ticket:
    """A player's ticket.

    main_numbers and euro_numbers are stored as frozen sets because order does
    not matter for lottery matching and immutability is useful in tests.
    """

    main_numbers: FrozenSet[int]
    euro_numbers: FrozenSet[int]


@dataclass(frozen=True)
class Draw:
    """A single Eurojackpot draw generated by the simulation engine."""

    main_numbers: FrozenSet[int]
    euro_numbers: FrozenSet[int]


@dataclass(frozen=True)
class EvaluationResult:
    """The result of comparing one ticket against one draw.

    prize_class stays optional because most tickets do not win anything.
    """

    matched_main: int
    matched_euro: int
    prize_class: str | None
